title: Mr.Fox
email: mr.fox@iran.ir
description: >- # this means to ignore newlines until "baseurl:"
  Ø³Ø§ÛŒØªÛŒ Ø¨Ø±Ø§ÛŒ Ø®ÙˆØ§Ù†Ø¯Ù† Devlog Ùˆ Ø®ÙˆØ§Ù†Ø¯Ù† Documents Ù†Ø±Ù… Ø§ÙØ²Ø§Ø±Ù‡Ø§ÛŒ Mr.Fox.
  Ø³Ø§ÛŒØªÛŒ Ø¨Ø±Ø§ÛŒ Ù‡ÙˆØ§Ø¯Ø§Ø±Ø§Ù† IT Ùˆ Ø¨Ø±Ù†Ø§Ù…Ù‡ Ù†ÙˆÛŒØ³ÛŒ ğŸ¦Š
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mr-fox-h.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
